apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp-netcore-k8s
    spec:
      containers:
      - name: webapp-netcore-k8s
        imagePullPolicy: Never
        image: webapp-netcore-k8s
        ports:
        - containerPort: 80
